
Import: Release 8.1.6.0.0 - Production on Tue Jul 18 10:27:47 2000

(c) Copyright 1999 Oracle Corporation.  All rights reserved.


Connected to: Oracle8i Enterprise Edition Release 8.1.6.0.0 - Production
With the Partitioning option
JServer Release 8.1.6.0.0 - Production

Export file created by EXPORT:V08.01.06 via conventional path
import done in US7ASCII character set and WE8ISO8859P1 NCHAR character set
import server uses WE8ISO8859P1 character set (possible charset conversion)
. importing TR's objects into TR
 "CREATE TABLE "DW_MERCHANT_DATE_SUM" ("DATE_ID" NUMBER(15, 0), "MERCHANT_SIT"
 "E_ID" NUMBER(15, 0), "MERCHANT_SITE_SID" NUMBER(15, 0), "STORE_PLACEMENT_CO"
 "UNT" NUMBER(15, 0), "PRODUCT_PLACEMENT_COUNT" NUMBER(15, 0), "AVG_PUBLISHER"
 "_CLICK_FEE_AMOUNT" NUMBER(6, 2), "BRAND_COUNT" NUMBER(15, 0), "FEATURED_PRO"
 "DUCT_COUNT" NUMBER(15, 0), "ANNOTATED_PRODUCT_COUNT" NUMBER(15, 0), "AVG_PR"
 "ODUCT_PRICE" NUMBER(15, 0), "PRODUCT_DETAIL_PAGE_COUNT" NUMBER(15, 0), "CLI"
 "CK_THROUGH_COUNT" NUMBER(15, 0), "TOTAL_REVENUE" NUMBER(8, 2), "ETL_ID" NUM"
 "BER(15, 0), "SUMMARY_DATE" DATE)  PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS "
 "255 NOLOGGING STORAGE(INITIAL 4235264 NEXT 4218880 MINEXTENTS 1 MAXEXTENTS "
 "2000 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLE"
 "SPACE "DATA1""
 "CREATE INDEX "DW_MERCHANT_DATE_SUM_FK1" ON "DW_MERCHANT_DATE_SUM" ("DATE_ID"
 "" , "SUMMARY_DATE" )  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 10"
 "64960 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2000 PCTINCREASE 0 FREELISTS 1 FR"
 "EELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "INDEX1" LOGGING"
 "CREATE INDEX "DW_MERCHANT_DATE_SUM_FK2" ON "DW_MERCHANT_DATE_SUM" ("MERCHAN"
 "T_SITE_ID" , "SUMMARY_DATE" )  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(I"
 "NITIAL 1331200 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2000 PCTINCREASE 0 FREEL"
 "ISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "INDEX1" LOGGING"
 "CREATE INDEX "DW_MERCHANT_DATE_SUM_FK2_TMP" ON "DW_MERCHANT_DATE_SUM" ("MER"
 "CHANT_SITE_SID" , "SUMMARY_DATE" )  PCTFREE 10 INITRANS 2 MAXTRANS 255 STOR"
 "AGE(INITIAL 798720 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2000 PCTINCREASE 0 F"
 "REELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "INDEX1" LOGGI"
 "NG"
 "CREATE INDEX "DW_MERCHANT_DATE_SUM_SDI" ON "DW_MERCHANT_DATE_SUM" ("SUMMARY"
 "_DATE" )  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 798720 NEXT 26"
 "2144 MINEXTENTS 1 MAXEXTENTS 2000 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS"
 " 1 BUFFER_POOL DEFAULT) TABLESPACE "INDEX1" LOGGING"
 "CREATE INDEX "DW_MERCHANT_DATE_SUM_PK" ON "DW_MERCHANT_DATE_SUM" ("SUMMARY_"
 "DATE" , "DATE_ID" , "MERCHANT_SITE_ID" )  PCTFREE 10 INITRANS 2 MAXTRANS 25"
 "5 STORAGE(INITIAL 1081344 NEXT 532480 MINEXTENTS 1 MAXEXTENTS 2000 PCTINCRE"
 "ASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "DATA1""
 " LOGGING"
 "CREATE BITMAP INDEX "DW_MERCHANT_DATE_SUM_B_DI" ON "DW_MERCHANT_DATE_SUM" ("
 ""DATE_ID" )  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 266240 NEXT"
 " 262144 MINEXTENTS 1 MAXEXTENTS 2000 PCTINCREASE 0 FREELISTS 1 FREELIST GRO"
 "UPS 1 BUFFER_POOL DEFAULT) TABLESPACE "INDEX1" LOGGING"
 "CREATE BITMAP INDEX "DW_MERCHANT_DATE_SUM_B_MSI" ON "DW_MERCHANT_DATE_SUM" "
 "("MERCHANT_SITE_ID" )  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 2"
 "66240 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2000 PCTINCREASE 0 FREELISTS 1 FR"
 "EELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "INDEX1" LOGGING"
 "ALTER TABLE "DW_MERCHANT_DATE_SUM" ENABLE CONSTRAINT "DW_MERCHANT_DATE_SUM_"
 "PK""
Import terminated successfully without warnings.
